### ISSUE TITLE
Wrong camera mirroring upon switching between front and back camera.

### ISSUE THREAD

**Issue by diogopereira** [skyway/skyway-android-sdk#57]
# Description of the problem
Upon switching the camera on the local media stream, it is impossible to determine which camera is being used creating issues where either the front camera or the back camera will be wrongfully mirrored.

# Environment

- SDK version: 2.6.0
- Device; Pixel 4
- OS: Android 11
- Network: Wifi

# Steps to reproduce the problem
Open the app, start a video call, change the camera.

# Expected behavior
The front camera should be mirrored while the back camera shouldn't.

# Other information (Log etc)
MediaStream class has a public function called `switchCamera`. This function creates a CameraSwitchHandler that, upon successfully changing the camera, will provide a flag called `isFrontCamera`. For some reason, the SDK does not expose this value making it impossible for the consumer app to determine if the new camera should be mirrored or not.

**Comment by ibuibu** [comment]
Thank you for raising the issue. Sorry for the delay in replying.

As you mentioned, the latest Android SDK does not currently implement a property variable to indicate the current camera.

As a work-around, you may want to try getUserMedia().
The camera orientation can be switched from the cameraPosition property of the optional MediaConstraints argument of getUserMedia(), so you will have to switch between FRONT and BACK each time.

In addition, We are planning to modify the sdk so that you can toggle between front and back even when the device has three cameras.

We apologize for the inconvenience, and thank you for your patience.
