### ISSUE TITLE
How convert MJpegInputStream to mediastream skyway??

### ISSUE THREAD

**Issue by trung0123** [skyway/skyway-android-sdk#71]
# Description of the problem

# Environment

- SDK version (ex. SDK v1.0.1,etc)
- Device (ex. Nexus6, etc)
- OS (ex. Android 7.0 etc)
- Network (Cable/DSL/Fiber + WiFi, MiFi, LTE, etc)

# Steps to reproduce the problem

# Expected behavior

# Other information (Log etc)

**Comment by trung0123** [comment]
I have camera 360 theta and I got stream 360 theta is MJpegInputStream, I want to convert this stream to mediastream and show stream theta direct to my room chat. I researched very much but I cannot find which method to convert stream theta to mediastream skyway. Skyway developers team can support me how convert stream 360 theta is MJpegInputStream??

**Comment by ibuibu** [comment]
It is difficult to acquire external camera video with this skyway-android-sdk, so it is not possible to realize your request.

On the other hand, the new version of SkyWay (https://skyway.ntt.com/en/) can input an external stream, so it may be possible to realize your request. We would be happy to give it a try.

Also, for questions like this, post in the community forum.
https://support.skyway.io/hc/en-us/community/topics

This issue is closed.
